language: elixir
elixir:
  - 1.8
otp_release:
  - 21.3
services:
  - postgresql
env:
  - TEST_YGGDRASIL_POSTGRES_DATABASE="travis_ci_test"
before_script:
  - psql -c "CREATE DATABASE $TEST_YGGDRASIL_POSTGRES_DATABASE" -U postgres
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix deps.compile
  - MIX_ENV=test mix compile
script:
  - MIX_ENV=test mix test
